sonar.projectKey=lof-proover
sonar.sources=src
sonar.language=rs
sonar.inclusions=src/**/*.rs
#test coverage
# sonar.rust.coverage.reportPaths=cobertura.xml 
# community.rust.cobertura.reportPaths=cobertura.xml
sonar.rust.cobertura.reportPaths=cobertura.xml
# sonar.coverageReportPaths=cobertura.xml
# community.rust.clippy.reportPaths=clippy.json